'use client';
import {useState,useRef} from 'react';
import {ArrowUpRight,ArrowRight,Upload,FileSpreadsheet,ShieldCheck,Download,Check,RotateCcw,LockKeyhole,EyeOff,Sparkles,KeyRound} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {readFile,pseudonymize,anonymize,reconcile,download,ID,ANONYMOUS_ID,type Dataset,type Loaded,type ColumnTreatment} from '@/lib/data';

type Journey='home'|'pseudonymize'|'anonymize';
function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
const treatmentLabels:Record<ColumnTreatment,string>={keep:'Conserver',remove:'Retirer',geo:'Géo',age:'Âge',salary:'Salaire',date:'Date → année'};
function TreatmentChoice({value,onChange,label}:{value:ColumnTreatment;onChange:(s:ColumnTreatment)=>void;label:string}){return <Select value={value} onValueChange={s=>onChange(s as ColumnTreatment)}><SelectTrigger aria-label={label} className="treatment-select"><SelectValue/></SelectTrigger><SelectContent>{(Object.keys(treatmentLabels) as ColumnTreatment[]).map(x=><SelectItem key={x} value={x}>{treatmentLabels[x]}</SelectItem>)}</SelectContent></Select>}
function FilePicker({title,onData,onError}:{title:string;onData:(d:Dataset|null)=>void;onError:(s:string)=>void}){
 const input=useRef<HTMLInputElement>(null);const [loaded,setLoaded]=useState<Loaded|null>(null);const [sheet,setSheet]=useState('');const [busy,setBusy]=useState(false);const [drag,setDrag]=useState(false);
 async function pick(file?:File){if(!file)return;setBusy(true);onData(null);setLoaded(null);onError('');try{const l=await readFile(file);setLoaded(l);const s=Object.keys(l.sheets)[0];setSheet(s);onData(l.sheets[s]);}catch(e){onError((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 return <div className="file-block"><input ref={input} type="file" accept=".csv,.json,.xls,.xlsx" className="sr-only" aria-label={title} onChange={e=>pick(e.target.files?.[0])}/><button disabled={busy} className={'dropzone '+(drag?'drag ':'')+(loaded?'has-file':'')} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files.length!==1){onError('Déposez un seul fichier à la fois.');return;}pick(e.dataTransfer.files[0]);}}>{loaded?<FileSpreadsheet size={30}/>:<Upload size={30}/>}<strong>{busy?'Lecture du fichier…':loaded?loaded.name:title}</strong><span>{loaded?'Cliquer pour remplacer le fichier':'Glissez votre fichier ici ou cliquez pour le choisir'}</span>{!loaded&&<small>CSV · JSON · XLS · XLSX — 20 Mo maximum</small>}</button>{loaded&&Object.keys(loaded.sheets).length>1&&<div className="sheet"><span>Feuille à traiter</span><Choice label="Feuille à traiter" value={sheet} options={Object.keys(loaded.sheets)} onChange={s=>{setSheet(s);onData(loaded.sheets[s]);}}/></div>}</div>
}
function Preview({data,hidden=[]}:{data:Dataset;hidden?:string[]}){return <div className="preview"><div className="preview-label"><span>{data.rows.length.toLocaleString('fr-FR')} lignes · {data.columns.length} colonnes</span><span>Aperçu : {Math.min(5,data.rows.length)} lignes</span></div><Table><TableHeader><TableRow>{data.columns.map(c=><TableHead className={hidden.includes(c)?'masked':''} key={c}>{c}{hidden.includes(c)&&<EyeOff size={13}/>}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.slice(0,5).map((r,i)=><TableRow key={i}>{data.columns.map(c=><TableCell title={String(r[c]??'')} className={hidden.includes(c)?'masked':''} key={c}>{String(r[c]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
function Steps({current,restore=false}:{current:number;restore?:boolean}){return <ol className="steps">{(restore?['Importer','Vérifier','Exporter']:['Importer','Choisir','Vérifier','Exporter']).map((s,i)=><li key={s} aria-current={current===i?'step':undefined} className={current>=i?'active':''}><span>{current>i?<Check size={15}/>:i+1}</span>{s}</li>)}</ol>}

export default function Page(){
 const [journey,setJourney]=useState<Journey>('home'),[pseudoMode,setPseudoMode]=useState('hide'),[step,setStep]=useState(0),[source,setSource]=useState<Dataset|null>(null),[treatments,setTreatments]=useState<Record<string,ColumnTreatment>>({}),[pair,setPair]=useState<Awaited<ReturnType<typeof pseudonymize>>|null>(null),[anonymous,setAnonymous]=useState<Dataset|null>(null),[mapping,setMapping]=useState<Dataset|null>(null),[result,setResult]=useState<Dataset|null>(null),[format,setFormat]=useState('csv'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resetKey,setResetKey]=useState(0),[generating,setGenerating]=useState(false);
 let report:ReturnType<typeof reconcile>|null=null,reportError='';if(mapping&&result){try{report=reconcile(mapping,result);}catch(e){reportError=(e as Error).message;}}
 function resetData(){setSource(null);setMapping(null);setResult(null);setTreatments({});setPair(null);setAnonymous(null);setStep(0);setError('');setNotice('');setResetKey(x=>x+1);}
 function goHome(){resetData();setJourney('home');setPseudoMode('hide');}
 function selectJourney(j:Journey){resetData();setJourney(j);setPseudoMode('hide');}
 function save(data:Dataset,suffix:string){try{download(data,format,suffix);setNotice('Téléchargement lancé.');setError('');}catch(e){setError((e as Error).message);}}
 async function generate(){if(!source)return;setGenerating(true);try{if(journey==='anonymize')setAnonymous(await anonymize(source,treatments));else setPair(await pseudonymize(source,treatments));setStep(2);setError('');}catch(e){setError((e as Error).message);}finally{setGenerating(false);}}
 const blocked=!report||report.duplicates>0||report.invalid>0||report.matched===0;
 const changed=source?.columns.filter(c=>(treatments[c]||'keep')!=='keep')||[];
 const removed=changed.filter(c=>treatments[c]==='remove');
 const generalized=changed.filter(c=>treatments[c]!=='remove');
 const output=journey==='anonymize'?anonymous:pair?.pseudonymized;
 const isAnon=journey==='anonymize';
 return <><header><button className="brand" onClick={goHome} aria-label="Yeitanize — accueil">yeitanize<span>✳</span></button><div className="header-right"><a href="https://www.yeita.fr/" target="_blank" rel="noreferrer">par yeita <ArrowUpRight size={17}/></a></div></header><main>
 <div className="intro"><div><p className="eyebrow">VOS DONNÉES, VOS RÈGLES.</p><h1>Partagez l’utile.<br/><em>Gardez le personnel.</em></h1></div><div className="local"><ShieldCheck size={32}/><div><strong>Ça reste chez vous.</strong><p>Vos fichiers sont traités dans votre navigateur.<br/>Aucune donnée de fichier n’est envoyée au serveur.</p></div></div></div>
 {journey==='home'&&<>
  <div className="journey-grid">
   <button className="journey-card anon-card" onClick={()=>selectJourney('anonymize')}><Sparkles size={28}/><span><strong>Anonymiser ma donnée</strong><p>Réduire ou supprimer les informations permettant d’identifier une personne. Le résultat est pensé pour être irréversible : aucune table de correspondance n’est créée.</p></span><ArrowRight/></button>
   <button className="journey-card pseudo-card" onClick={()=>selectJourney('pseudonymize')}><KeyRound size={28}/><span><strong>Pseudonymiser ma donnée</strong><p>Masquer ou généraliser certaines données tout en conservant séparément la clé permettant de retrouver les valeurs d’origine.</p></span><ArrowRight/></button>
  </div>
  <div className="legal-card"><LockKeyhole size={19}/><div><strong>À savoir avant de commencer</strong><p>La CNIL distingue clairement anonymisation et pseudonymisation. Une anonymisation n’est effective que si la réidentification devient impossible en pratique. Yeitanize fournit des transformations techniques mais ne peut pas garantir, à lui seul, qu’un jeu de données est réellement anonyme ou qu’un traitement est conforme au RGPD. L’utilisateur reste responsable des finalités et usages de ses données.</p><div className="legal-links"><a href="https://www.cnil.fr/fr/identifier-les-donnees-personnelles" target="_blank" rel="noreferrer">Différence anonymisation / pseudonymisation — CNIL <ArrowUpRight size={14}/></a><a href="https://www.cnil.fr/fr/reglement-europeen-protection-donnees" target="_blank" rel="noreferrer">Consulter le RGPD — CNIL <ArrowUpRight size={14}/></a></div></div></div>
 </>}
 {journey==='pseudonymize'&&<>
  <div className="privacy-warning"><LockKeyhole size={18}/><p><strong>Pseudonymiser ne veut pas dire anonymiser.</strong> Le fichier généré peut toujours contenir des données personnelles et rester soumis au RGPD.</p></div>
  <Tabs value={pseudoMode} onValueChange={m=>{setPseudoMode(m);setError('');setNotice('')}}><div className="toolbar"><TabsList className="mode-tabs"><TabsTrigger value="hide"><EyeOff size={18}/> Pseudonymiser</TabsTrigger><TabsTrigger value="restore"><RotateCcw size={18}/> Restaurer</TabsTrigger></TabsList><button className="text-button" onClick={goHome}>Changer de mode</button></div>
   <TabsContent value="hide">{renderProcess()}</TabsContent>
   <TabsContent value="restore"><section className="workspace"><Steps current={report?1:0} restore/><div className="restore-work"><span className="kicker">ON RECOLLE LES MORCEAUX</span><h2>Retrouvez vos données.</h2><p>Importez votre fichier de correspondance et le résultat de votre IA.</p><div className="two-files"><div><h3>01. Votre fichier de correspondance</h3><FilePicker key={'m'+resetKey} title="Choisir le mapping" onData={setMapping} onError={setError}/></div><div><h3>02. Le résultat de l’IA</h3><FilePicker key={'r'+resetKey} title="Choisir le résultat IA" onData={setResult} onError={setError}/></div></div>{reportError&&<p className="error" role="alert">{reportError}</p>}{report&&<><div className="stats"><div><strong>{report.matched}</strong>correspondances</div><div><strong>{report.missing.length}</strong>absentes du résultat</div><div><strong>{report.unknown.length}</strong>identifiants inconnus</div><div><strong>{report.duplicates+report.invalid}</strong>doublons ou IDs invalides</div></div>{blocked?<p className="error">Restauration bloquée : corrigez les identifiants vides ou dupliqués, et vérifiez qu’au moins un identifiant correspond exactement.</p>:<><p className="hint">Les colonnes originales viennent du mapping. Les colonnes <code>_pseudonymized</code> disparaissent et seules les nouvelles colonnes produites par l’IA sont ajoutées.</p><Preview data={report.data}/><div className="actions"><Choice label="Format du fichier restauré" value={format} options={['csv','json','xls','xlsx']} onChange={setFormat}/><button className="primary" onClick={()=>save(report!.data,'restored')}><Download size={18}/> Télécharger les données restaurées</button></div></>}</>}</div></section></TabsContent>
  </Tabs>
 </>}
 {journey==='anonymize'&&<><div className="privacy-warning anon-warning"><ShieldCheck size={18}/><p><strong>Une anonymisation réelle dépend du contexte.</strong> Yeitanize applique ici de la suppression et de la généralisation, sans conserver de clé de retour. Vérifiez néanmoins que les données restantes ne permettent pas de réidentifier une personne.</p></div><div className="toolbar"><span></span><button className="text-button" onClick={goHome}>Changer de mode</button></div>{renderProcess()}</>}
 {error&&<div role="alert" className="error global-message">{error}</div>}{notice&&<div role="status" className="notice global-message"><Check size={17}/>{notice}</div>}
 {journey!=='home'&&<><div className="footnote"><LockKeyhole size={16}/><span>Aucun fichier conservé après fermeture ou rafraîchissement.</span></div><details className="limits"><summary>Formats et limites du POC</summary><p>CSV en UTF-8. JSON : tableau d’objets avec champs simples. Excel : une feuille à la fois. 20 Mo, 100 000 lignes et 500 colonnes maximum. Pour « Géo », un code postal est réduit en département à partir de son préfixe ; un département est réduit en région ; une ville peut être résolue via un référentiel public chargé dans le navigateur, sans transmettre les valeurs du fichier.</p></details></>}
 </main><footer><span>Fait avec soin, par <a href="https://www.yeita.fr/" target="_blank" rel="noreferrer">yeita ↗</a></span></footer></>;

 function renderProcess(){
  const titles=isAnon?['Importez votre fichier.','Que faut-il généraliser ?','Vérifiez le résultat.','Votre fichier est prêt.']:['Importez votre fichier.','Que garde-t-on pour l’IA ?','Vérifiez ce qui sera partagé.','Deux fichiers. Deux usages.'];
  const desc=isAnon?['Votre tableau est le point de départ.','Retirez les identifiants et généralisez les données qui doivent rester utiles à l’analyse.','Aucune table de correspondance n’est générée : ces transformations sont irréversibles dans Yeitanize.','Téléchargez le fichier généralisé avant de fermer cette page.']:['Votre tableau est le point de départ. On s’occupe de la suite.','Pour chaque colonne, choisissez de la conserver, la retirer ou réduire sa précision.','Les données sélectionnées ont été retirées ou pseudonymisées et chaque ligne a son identifiant.','Téléchargez les deux fichiers avant de fermer cette page.'];
  return <section className="workspace"><Steps current={step}/><div className="work-grid"><div className="main-work"><div className="section-title"><span className="kicker">0{step+1} / {['LE POINT DE DÉPART','À VOUS DE CHOISIR','UN DERNIER REGARD','C’EST PRÊT'][step]}</span><h2>{titles[step]}</h2><p>{desc[step]}</p></div>
  {step===0&&<><FilePicker key={resetKey} title="Choisir mon fichier" onError={setError} onData={d=>{setSource(d);setTreatments({});setPair(null);setAnonymous(null);if(d)setFormat(d.format)}}/>{source&&<><Preview data={source}/><div className="actions"><button className="primary" onClick={()=>setStep(1)}>Choisir le traitement <ArrowRight size={18}/></button></div></>}</>}
  {step===1&&source&&<><div className="selection-head"><strong>{changed.length} colonne{changed.length>1?'s':''} traitée{changed.length>1?'s':''}</strong><button className="text-button" onClick={()=>setTreatments({})}>Tout conserver</button></div><div className="treatment-help"><span>Géo : code postal/ville → département, département → région</span><span>Âge : 32 → 30-35 ans</span><span>Salaire : 77 863,93 → 75 000 - 80 000</span><span>Date : 14/06/1992 → 1992</span></div><div className="columns">{source.columns.map(c=>{const treatment=treatments[c]||'keep';return <div key={c} className={'column '+(treatment!=='keep'?'selected':'')}><span><strong>{c}</strong><small>{source.rows.slice(0,2).map(r=>String(r[c]??'—')).join(' · ')}</small></span><TreatmentChoice label={'Traitement de '+c} value={treatment} onChange={v=>setTreatments(t=>({...t,[c]:v}))}/></div>})}</div><Preview data={source} hidden={removed}/><div className="actions"><button className="secondary" onClick={()=>setStep(0)}>Retour</button><button className="primary" disabled={!changed.length||generating} onClick={generate}>{generating?(isAnon?'Anonymisation…':'Pseudonymisation…'):'Vérifier mon fichier'} {!generating&&<ArrowRight size={18}/>}</button></div></>}
  {step===2&&output&&<><div className="summary-strip"><span><strong>{removed.length}</strong> colonne{removed.length>1?'s':''} retirée{removed.length>1?'s':''}</span><span><strong>{generalized.length}</strong> colonne{generalized.length>1?'s':''} généralisée{generalized.length>1?'s':''}</span><span><strong>{output.rows.length}</strong> identifiants techniques créés</span></div><Preview data={output}/><p className="hint">{isAnon?<>L’identifiant <code>{ANONYMOUS_ID}</code> est aléatoire, n’est rattaché à aucune donnée d’origine et sert uniquement à faciliter les traitements ultérieurs. Aucune table de correspondance n’est créée.</>:<>Les colonnes transformées portent le suffixe <code>_pseudonymized</code>. Relisez aussi les champs conservés : ils peuvent encore contenir des informations personnelles.</>}</p><div className="actions"><button className="secondary" onClick={()=>setStep(1)}>Modifier ma sélection</button><button className="primary" onClick={()=>setStep(3)}>Passer au téléchargement <ArrowRight size={18}/></button></div></>}
  {step===3&&output&&<><div className="format-row"><span>Format des fichiers</span><Choice label="Format d’export" value={format} options={['csv','json','xls','xlsx']} onChange={setFormat}/></div>{isAnon?<div className="export-card green"><ShieldCheck/><div><h3>Votre fichier généralisé</h3><p>{output.columns.length} colonnes, dont <code>{ANONYMOUS_ID}</code>. Aucune clé de restauration n’est générée.</p></div><button className="primary" onClick={()=>save(output,'anonymized')}><Download size={18}/> Télécharger</button></div>:<><div className="export-card green"><EyeOff/><div><h3>Le fichier pseudonymisé pour votre IA</h3><p>{output.columns.length} colonnes, dont l’identifiant de pseudonymisation.</p></div><button className="primary" onClick={()=>save(output,'pseudonymized')}><Download size={18}/> Télécharger</button></div><div className="export-card pink"><LockKeyhole/><div><h3>Votre fichier de correspondance</h3><p>Il contient toutes vos données originales.<br/><strong>Gardez-le. Ne le transmettez pas à l’IA.</strong></p></div><button className="secondary" onClick={()=>pair&&save(pair.mapping,'mapping')}><Download size={18}/> Télécharger</button></div><p className="hint">Demandez à l’IA de conserver exactement la colonne <code>{ID}</code>.</p><button className="text-button" onClick={()=>setPseudoMode('restore')}>J’ai mon résultat IA, restaurer les données <ArrowRight size={17}/></button></>}</>}
  </div><aside><span className="aside-icon">✳</span><h3>{isAnon?'Moins précis.\nPlus difficile à identifier.':'Le bon contenu.\nAux bonnes mains.'}</h3><ol>{isAnon?<><li><b>Vous retirez.</b><p>Supprimez les colonnes qui n’ont pas besoin de sortir.</p></li><li><b>Vous généralisez.</b><p>Âge, salaire, date et géographie perdent volontairement en précision.</p></li><li><b>Vous ne gardez aucune clé.</b><p>Yeitanize ne génère aucun fichier permettant de revenir aux valeurs originales.</p></li><li><b>Vous gardez un identifiant technique.</b><p><code>{ANONYMOUS_ID}</code> permet de suivre une ligne sans la rattacher à l’original.</p></li></>:<><li><b>Vous choisissez.</b><p>Chaque colonne peut être conservée, retirée ou pseudonymisée.</p></li><li><b>Vous réduisez la précision.</b><p>Géographie, âge, salaire et date peuvent être transformés.</p></li><li><b>Vous gardez la clé.</b><p>Un fichier séparé conserve vos données originales.</p></li><li><b>Vous retrouvez vos données.</b><p>Après l’IA, les vraies valeurs remplacent les colonnes transformées.</p></li></>}</ol><div className="aside-note"><LockKeyhole size={16}/><p>{isAnon?'La généralisation réduit le risque mais ne garantit pas, seule, l’anonymat effectif.':'Une pseudonymisation réversible, pas une garantie d’anonymat.'}</p></div></aside></div></section>;
 }
}
