'use client';
import {useState,useRef} from 'react';
import {ArrowUpRight,ArrowRight,Upload,FileSpreadsheet,ShieldCheck,Download,Check,RotateCcw,LockKeyhole,EyeOff} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {readFile,pseudonymize,reconcile,download,ID,type Dataset,type Loaded} from '@/lib/data';
function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
function FilePicker({title,onData,onError}:{title:string;onData:(d:Dataset|null)=>void;onError:(s:string)=>void}){
 const input=useRef<HTMLInputElement>(null);const [loaded,setLoaded]=useState<Loaded|null>(null);const [sheet,setSheet]=useState('');const [busy,setBusy]=useState(false);const [drag,setDrag]=useState(false);
 async function pick(file?:File){if(!file)return;setBusy(true);onData(null);setLoaded(null);onError('');try{const l=await readFile(file);setLoaded(l);const s=Object.keys(l.sheets)[0];setSheet(s);onData(l.sheets[s]);}catch(e){onError((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 return <div className="file-block"><input ref={input} type="file" accept=".csv,.json,.xls,.xlsx" className="sr-only" aria-label={title} onChange={e=>pick(e.target.files?.[0])}/><button disabled={busy} className={'dropzone '+(drag?'drag ':'')+(loaded?'has-file':'')} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files.length!==1){onError('Déposez un seul fichier à la fois.');return;}pick(e.dataTransfer.files[0]);}}>{loaded?<FileSpreadsheet size={30}/>:<Upload size={30}/>}<strong>{busy?'Lecture du fichier…':loaded?loaded.name:title}</strong><span>{loaded?'Cliquer pour remplacer le fichier':'Glissez votre fichier ici ou cliquez pour le choisir'}</span>{!loaded&&<small>CSV · JSON · XLS · XLSX — 20 Mo maximum</small>}</button>{loaded&&Object.keys(loaded.sheets).length>1&&<div className="sheet"><span>Feuille à traiter</span><Choice label="Feuille à traiter" value={sheet} options={Object.keys(loaded.sheets)} onChange={s=>{setSheet(s);onData(loaded.sheets[s]);}}/></div>}</div>
}
function Preview({data,hidden=[]}:{data:Dataset;hidden?:string[]}){return <div className="preview"><div className="preview-label"><span>{data.rows.length.toLocaleString('fr-FR')} lignes · {data.columns.length} colonnes</span><span>Aperçu : {Math.min(5,data.rows.length)} lignes</span></div><Table><TableHeader><TableRow>{data.columns.map(c=><TableHead className={hidden.includes(c)?'masked':''} key={c}>{c}{hidden.includes(c)&&<EyeOff size={13}/>}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.slice(0,5).map((r,i)=><TableRow key={i}>{data.columns.map(c=><TableCell title={String(r[c]??'')} className={hidden.includes(c)?'masked':''} key={c}>{String(r[c]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
function Steps({current,restore=false}:{current:number;restore?:boolean}){return <ol className="steps">{(restore?['Importer','Vérifier','Exporter']:['Importer','Choisir','Vérifier','Exporter']).map((s,i)=><li key={s} aria-current={current===i?'step':undefined} className={current>=i?'active':''}><span>{current>i?<Check size={15}/>:i+1}</span>{s}</li>)}</ol>}
export default function Page(){
 const [mode,setMode]=useState('hide'),[step,setStep]=useState(0),[source,setSource]=useState<Dataset|null>(null),[hidden,setHidden]=useState<string[]>([]),[pair,setPair]=useState<ReturnType<typeof pseudonymize>|null>(null),[mapping,setMapping]=useState<Dataset|null>(null),[result,setResult]=useState<Dataset|null>(null),[format,setFormat]=useState('csv'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resetKey,setResetKey]=useState(0);
 let report:ReturnType<typeof reconcile>|null=null,reportError='';if(mapping&&result){try{report=reconcile(mapping,result);}catch(e){reportError=(e as Error).message;}}
 function reset(){setSource(null);setMapping(null);setResult(null);setHidden([]);setPair(null);setStep(0);setError('');setNotice('');setResetKey(x=>x+1);}
 function save(data:Dataset,suffix:string){try{download(data,format,suffix);setNotice('Téléchargement lancé.');setError('');}catch(e){setError((e as Error).message);}}
 function generate(){try{if(source){setPair(pseudonymize(source,hidden));setStep(2);setError('');}}catch(e){setError((e as Error).message);}}
 const blocked=!report||report.duplicates>0||report.invalid>0||report.matched===0;
 return <><header><button className="brand" onClick={()=>{reset();setMode('hide')}} aria-label="Yeitanize — accueil">yeitanize<span>✳</span></button><div className="header-right"><a href="https://www.yeita.fr/" target="_blank" rel="noreferrer">par yeita <ArrowUpRight size={17}/></a></div></header><main><div className="intro"><div><p className="eyebrow">VOS DONNÉES, VOS RÈGLES.</p><h1>Partagez l’utile.<br/><em>Gardez le personnel.</em></h1></div><div className="local"><ShieldCheck size={32} aria-hidden="true"/><div><strong>Ça reste chez vous.</strong><p>Vos fichiers sont traités dans votre navigateur.<br/>Aucune donnée de fichier n’est envoyée au serveur.</p></div></div></div>
 <Tabs value={mode} onValueChange={m=>{setMode(m);setError('');setNotice('')}}><div className="toolbar"><TabsList className="mode-tabs"><TabsTrigger value="hide"><EyeOff size={18}/> Anonymiser un fichier</TabsTrigger><TabsTrigger value="restore"><RotateCcw size={18}/> Restaurer mes données</TabsTrigger></TabsList><button className="text-button" onClick={reset}><RotateCcw size={15}/>Tout effacer</button></div>
 <TabsContent value="hide"><section className="workspace"><Steps current={step}/><div className="work-grid"><div className="main-work"><div className="section-title"><span className="kicker">0{step+1} / {['LE POINT DE DÉPART','À VOUS DE CHOISIR','UN DERNIER REGARD','C’EST PRÊT'][step]}</span><h2>{['Importez votre fichier.','Que garde-t-on pour l’IA ?','Vérifiez ce qui sera partagé.','Deux fichiers. Deux usages.'][step]}</h2><p>{['Votre tableau est le point de départ. On s’occupe de la suite.','Cochez les colonnes à retirer. Rien n’est sélectionné à votre place.','Les colonnes choisies ont été retirées et chaque ligne a son identifiant.','Téléchargez les deux fichiers avant de fermer cette page.'][step]}</p></div>
 {step===0&&<><FilePicker key={resetKey} title="Choisir mon fichier" onError={setError} onData={d=>{setSource(d);setHidden([]);setPair(null);if(d)setFormat(d.format)}}/>{source&&<><Preview data={source}/><div className="actions"><button className="primary" onClick={()=>setStep(1)}>Choisir les colonnes <ArrowRight size={18}/></button></div></>}</>}
 {step===1&&source&&<><div className="selection-head"><strong>{hidden.length} colonne{hidden.length>1?'s':''} à masquer</strong><button className="text-button" onClick={()=>setHidden(hidden.length===source.columns.length?[]:source.columns)}>{hidden.length===source.columns.length?'Tout désélectionner':'Tout sélectionner'}</button></div><div className="columns">{source.columns.map((c,i)=><label key={c} className={'column '+(hidden.includes(c)?'selected':'')} htmlFor={'col-'+i}><Checkbox id={'col-'+i} checked={hidden.includes(c)} onCheckedChange={v=>setHidden(h=>v?[...h,c]:h.filter(x=>x!==c))}/><span><strong>{c}</strong><small>{source.rows.slice(0,2).map(r=>String(r[c]??'—')).join(' · ')}</small></span>{hidden.includes(c)&&<EyeOff size={17}/>}</label>)}</div><Preview data={source} hidden={hidden}/><div className="actions"><button className="secondary" onClick={()=>setStep(0)}>Retour</button><button className="primary" disabled={!hidden.length} onClick={generate}>Vérifier mon fichier <ArrowRight size={18}/></button></div></>}
 {step===2&&pair&&<><div className="summary-strip"><span><strong>{hidden.length}</strong> colonnes retirées</span><span><strong>{pair.anonymous.rows.length}</strong> identifiants créés</span></div><Preview data={pair.anonymous}/><p className="hint">Relisez aussi les champs conservés : ils peuvent encore contenir des informations personnelles.</p><div className="actions"><button className="secondary" onClick={()=>setStep(1)}>Modifier ma sélection</button><button className="primary" onClick={()=>setStep(3)}>Passer au téléchargement <ArrowRight size={18}/></button></div></>}
 {step===3&&pair&&<><div className="format-row"><span>Format des fichiers</span><Choice label="Format d’export" value={format} options={['csv','json','xls','xlsx']} onChange={setFormat}/></div><div className="export-card green"><EyeOff/><div><h3>Le fichier pour votre IA</h3><p>{pair.anonymous.columns.length} colonnes conservées, dont l’identifiant.</p></div><button className="primary" onClick={()=>save(pair.anonymous,'anonymized')}><Download size={18}/> Télécharger</button></div><div className="export-card pink"><LockKeyhole/><div><h3>Votre fichier de correspondance</h3><p>Il contient toutes vos données originales.<br/><strong>Gardez-le. Ne le transmettez pas à l’IA.</strong></p></div><button className="secondary" onClick={()=>save(pair.mapping,'mapping')}><Download size={18}/> Télécharger</button></div><p className="hint">Demandez à l’IA de conserver exactement la colonne <code>{ID}</code>, y compris les majuscules et minuscules.</p><button className="text-button" onClick={()=>setMode('restore')}>J’ai mon résultat IA, restaurer les données <ArrowRight size={17}/></button></>}
 </div><aside><span className="aside-icon">✳</span><h3>Le bon contenu.<br/>Aux bonnes mains.</h3><ol><li><b>Vous choisissez.</b><p>Les colonnes à masquer, c’est vous qui les décidez.</p></li><li><b>Vous gardez la clé.</b><p>Un fichier séparé conserve vos données originales.</p></li><li><b>Vous retrouvez vos données.</b><p>Après l’IA, l’identifiant fait le lien.</p></li></ol><div className="aside-note"><LockKeyhole size={16}/><p>Un masquage réversible, pas une garantie d’anonymat.</p></div></aside></div></section></TabsContent>
 <TabsContent value="restore"><section className="workspace"><Steps current={report?1:0} restore/><div className="restore-work"><span className="kicker">ON RECOLLE LES MORCEAUX</span><h2>Retrouvez vos données.</h2><p>Importez votre fichier de correspondance et le résultat de votre IA.</p><div className="two-files"><div><h3>01. Votre fichier de correspondance</h3><FilePicker key={'m'+resetKey} title="Choisir le mapping" onData={setMapping} onError={setError}/></div><div><h3>02. Le résultat de l’IA</h3><FilePicker key={'r'+resetKey} title="Choisir le résultat IA" onData={setResult} onError={setError}/></div></div>{reportError&&<p className="error" role="alert">{reportError}</p>}{report&&<><div className="stats"><div><strong>{report.matched}</strong>correspondances</div><div><strong>{report.missing.length}</strong>absentes du résultat</div><div><strong>{report.unknown.length}</strong>identifiants inconnus</div><div><strong>{report.duplicates+report.invalid}</strong>doublons ou IDs invalides</div></div>{blocked?<p className="error">Restauration bloquée : corrigez les identifiants vides ou dupliqués, et vérifiez qu’au moins un identifiant correspond exactement.</p>:<><p className="hint">Toutes les lignes du mapping sont conservées, dans leur ordre d’origine. Les lignes absentes du résultat ont des champs IA vides. Les identifiants inconnus sont exclus.</p>{(report.unknown.length>0||report.missing.length>0)&&<details><summary>Voir les identifiants concernés</summary><p>Absents : {report.missing.join(', ')||'Aucun'}</p><p>Inconnus : {report.unknown.join(', ')||'Aucun'}</p></details>}{Object.entries(report.renames).some(([a,b])=>a!==b)&&<p className="hint">Colonnes renommées pour protéger l’original : {Object.entries(report.renames).filter(([a,b])=>a!==b).map(([a,b])=>a+' → '+b).join(', ')}.</p>}<Preview data={report.data}/><div className="actions"><Choice label="Format du fichier restauré" value={format} options={['csv','json','xls','xlsx']} onChange={setFormat}/><button className="primary" onClick={()=>save(report!.data,'restored')}><Download size={18}/> Télécharger les données restaurées</button></div></>}</>}</div></section></TabsContent></Tabs>
 {error&&<div role="alert" className="error global-message">{error}</div>}{notice&&<div role="status" className="notice global-message"><Check size={17}/>{notice}</div>}<div className="footnote"><LockKeyhole size={16}/><span>Aucun fichier conservé après fermeture ou rafraîchissement. Pensez à télécharger votre mapping.</span></div><details className="limits"><summary>Formats et limites du POC</summary><p>CSV en UTF-8 (virgule, point-virgule ou tabulation). JSON : tableau d’objets avec champs simples. Excel : une feuille à la fois, première ligne utilisée comme en-tête ; export des valeurs uniquement, sans mise en forme, macros ou formules. 20 Mo, 100 000 lignes et 500 colonnes maximum. L’export CSV neutralise les textes pouvant être interprétés comme des formules ; préférez JSON ou XLSX pour conserver ces textes à l’identique.</p></details></main><footer><span>Fait avec soin, par <a href="https://www.yeita.fr/" target="_blank" rel="noreferrer">yeita ↗</a></span></footer></>;
}
